In [6]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [7]:
df = sns.load_dataset("titanic")

In [8]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [9]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [11]:
df.drop(['class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive'], axis=1, inplace = True)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   sex       891 non-null    object
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64
 5   parch     891 non-null    int64
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object
 8   alone     891 non-null    bool
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 56.7+ KB

In [13]:
df['age'].fillna(df["age"].mean(),inplace=True)

In [14]:
df.dropna(subset= ["embarked"],inplace = True)

In [15]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [16]:
df.head()

   survived  pclass     sex   age  sibsp  parch     fare embarked  alone
0         0       3    male  22.0      1      0   7.2500        S  False
1         1       1  female  38.0      1      0  71.2833        C  False
2         1       3  female  26.0      0      0   7.9250        S   True
3         1       1  female  35.0      1      0  53.1000        S  False
4         0       3    male  35.0      0      0   8.0500        S   True

In [17]:
df['sex']= le.fit_transform(df['sex'])
df['embarked'] =le.fit_transform(df['embarked'])

In [18]:
df.head()
df = df.astype(int)

In [19]:
df.head()

   survived  pclass  sex  age  sibsp  parch  fare  embarked  alone
0         0       3    1   22      1      0     7         2      0
1         1       1    0   38      1      0    71         0      0
2         1       3    0   26      0      0     7         2      1
3         1       1    0   35      1      0    53         2      0
4         0       3    1   35      0      0     8         2      1

In [20]:
X = df.drop('survived', axis=1)
y = df['survived']

In [21]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [22]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [23]:
y_pred = model.predict(X_test)

In [24]:
y_pred

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

In [25]:
y_test

281    0
435    1
39     1
418    0
585    1
      ..
433    0
807    0
25     1
85     1
10     1
Name: survived, Length: 178, dtype: int64

In [26]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [27]:
accuracy_score(y_test, y_pred)

0.8033707865168539

In [28]:
confusion_matrix(y_test, y_pred)

array([[90, 19],
       [16, 53]])

In [29]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.85      0.83      0.84       109
           1       0.74      0.77      0.75        69

    accuracy                           0.80       178
   macro avg       0.79      0.80      0.79       178
weighted avg       0.81      0.80      0.80       178

In [30]:
df

     survived  pclass  sex  age  sibsp  parch  fare  embarked  alone
0           0       3    1   22      1      0     7         2      0
1           1       1    0   38      1      0    71         0      0
2           1       3    0   26      0      0     7         2      1
3           1       1    0   35      1      0    53         2      0
4           0       3    1   35      0      0     8         2      1
..        ...     ...  ...  ...    ...    ...   ...       ...    ...
886         0       2    1   27      0      0    13         2      1
887         1       1    0   19      0      0    30         2      1
888         0       3    0   29      1      2    23         2      0
889         1       1    1   26      0      0    30         0      1
890         0       3    1   32      0      0     7         1      1

[889 rows x 9 columns]

In [31]:
X_test

     pclass  sex  age  sibsp  parch  fare  embarked  alone
281       3    1   28      0      0     7         2      1
435       1    0   14      1      2   120         2      0
39        3    0   14      1      0    11         0      0
418       2    1   30      0      0    13         2      1
585       1    0   18      0      2    79         2      0
..      ...  ...  ...    ...    ...   ...       ...    ...
433       3    1   17      0      0     7         2      1
807       3    0   18      0      0     7         2      1
25        3    0   38      1      5    31         2      0
85        3    0   33      3      0    15         2      0
10        3    0    4      1      1    16         2      0

[178 rows x 8 columns]

In [32]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [33]:
X_train_sc = sc.fit_transform(X_train)
X_test_sc = sc.transform(X_test)

In [34]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train_sc, y_train)

KNeighborsClassifier()

In [35]:
y_pred_knn = knn.predict(X_test_sc)

In [36]:
accuracy_score(y_test, y_pred)

0.8033707865168539

In [37]:
print(classification_report(y_test, y_pred_knn))

              precision    recall  f1-score   support

           0       0.84      0.82      0.83       109
           1       0.72      0.75      0.74        69

    accuracy                           0.79       178
   macro avg       0.78      0.79      0.78       178
weighted avg       0.79      0.79      0.79       178

In [38]:
X_test

     pclass  sex  age  sibsp  parch  fare  embarked  alone
281       3    1   28      0      0     7         2      1
435       1    0   14      1      2   120         2      0
39        3    0   14      1      0    11         0      0
418       2    1   30      0      0    13         2      1
585       1    0   18      0      2    79         2      0
..      ...  ...  ...    ...    ...   ...       ...    ...
433       3    1   17      0      0     7         2      1
807       3    0   18      0      0     7         2      1
25        3    0   38      1      5    31         2      0
85        3    0   33      3      0    15         2      0
10        3    0    4      1      1    16         2      0

[178 rows x 8 columns]

In [39]:
%whos

Variable                 Type                      Data/Info
------------------------------------------------------------
DecisionTreeClassifier   ABCMeta                   <class 'sklearn.tree._cla<...>.DecisionTreeClassifier'>
KNeighborsClassifier     ABCMeta                   <class 'sklearn.neighbors<...>on.KNeighborsClassifier'>
LabelEncoder             type                      <class 'sklearn.preproces<...>ing._label.LabelEncoder'>
LogisticRegression       type                      <class 'sklearn.linear_mo<...>stic.LogisticRegression'>
StandardScaler           type                      <class 'sklearn.preproces<...>ng._data.StandardScaler'>
X                        DataFrame                      pclass  sex  age  si<...>n\n[889 rows x 8 columns]
X_test                   DataFrame                      pclass  sex  age  si<...>n\n[178 rows x 8 columns]
X_test_sc                ndarray                   178x8: 1424 elems, type `float64`, 11392 bytes
X_train                  DataFrame                      pclass  sex  age  si<...>n\n[711 rows x 8 columns]
X_train_sc               ndarray                   711x8: 5688 elems, type `float64`, 45504 bytes
accuracy_score           function                  <function accuracy_score at 0x7ce020f259e0>
classification_report    function                  <function classification_<...>report at 0x7ce020f26e80>
confusion_matrix         function                  <function confusion_matrix at 0x7ce020f25b20>
df                       DataFrame                      survived  pclass  se<...>n\n[889 rows x 9 columns]
knn                      KNeighborsClassifier      KNeighborsClassifier()
le                       LabelEncoder              LabelEncoder()
model                    LogisticRegression        LogisticRegression()
model_DT                 DecisionTreeClassifier    DecisionTreeClassifier(random_state=42)
np                       module                    <module 'numpy' from '/us<...>kages/numpy/__init__.py'>
pd                       module                    <module 'pandas' from '/u<...>ages/pandas/__init__.py'>
plt                      module                    <module 'matplotlib.pyplo<...>es/matplotlib/pyplot.py'>
sc                       StandardScaler            StandardScaler()
sns                      module                    <module 'seaborn' from '/<...>ges/seaborn/__init__.py'>
train_test_split         function                  <function train_test_split at 0x7ce02099e160>
warnings                 module                    <module 'warnings' from '<...>/python3.12/warnings.py'>
y                        Series                    0      0\n1      1\n2    <...>Length: 889, dtype: int64
y_pred                   ndarray                   178: 178 elems, type `int64`, 1424 bytes
y_pred_knn               ndarray                   178: 178 elems, type `int64`, 1424 bytes
y_test                   Series                    281    0\n435    1\n39   <...>Length: 178, dtype: int64
y_train                  Series                    708    1\n240    0\n382  <...>Length: 711, dtype: int64

In [40]:
from sklearn.naive_bayes import GaussianNB

In [41]:
model_NB = GaussianNB()
model_NB.fit(X_train, y_train)

GaussianNB()

In [42]:
y_pred_NB = model_NB.predict(X_test)

In [43]:
y_pred_NB

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

In [44]:
accuracy_score(y_test, y_pred_NB)

0.7752808988764045

In [45]:
confusion_matrix(y_test, y_pred_NB)

array([[84, 25],
       [15, 54]])

In [46]:
print(classification_report(y_test, y_pred_NB))

              precision    recall  f1-score   support

           0       0.85      0.77      0.81       109
           1       0.68      0.78      0.73        69

    accuracy                           0.78       178
   macro avg       0.77      0.78      0.77       178
weighted avg       0.78      0.78      0.78       178

In [47]:
from sklearn.tree import DecisionTreeClassifier

In [48]:
model_DT = DecisionTreeClassifier(random_state=42)

In [51]:
model_DT.fit(X_train_sc, y_train)

DecisionTreeClassifier(random_state=42)

In [53]:
y_pred_DT = model_DT.predict(X_test_sc)

In [54]:
y_pred_DT

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 0])

In [55]:
accuracy_score(y_test, y_pred_DT)

0.8033707865168539

In [56]:
confusion_matrix(y_test, y_pred_DT)

array([[90, 19],
       [16, 53]])

In [57]:
print(classification_report(y_test, y_pred_DT))

              precision    recall  f1-score   support

           0       0.85      0.83      0.84       109
           1       0.74      0.77      0.75        69

    accuracy                           0.80       178
   macro avg       0.79      0.80      0.79       178
weighted avg       0.81      0.80      0.80       178

In [58]:
from sklearn.svm import SVC

In [60]:
model_SVC = SVC(kernel='rbf', random_state=42)
model_SVC.fit(X_train_sc, y_train)

SVC(random_state=42)

In [72]:
y_pred_svc = model_SVC.predict(X_test_sc)

In [73]:
y_pred_svc

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

In [74]:
accuracy_score(y_test, y_pred_svc)

0.8146067415730337

In [69]:
confusion_matrix(y_test, y_pred_svc)

array([[90, 19],
       [16, 53]])

In [70]:
print(classification_report(y_test, y_pred_svc))

              precision    recall  f1-score   support

           0       0.85      0.83      0.84       109
           1       0.74      0.77      0.75        69

    accuracy                           0.80       178
   macro avg       0.79      0.80      0.79       178
weighted avg       0.81      0.80      0.80       178